meta_product_name: "Last one"
meta_title: "Last one - Just stop already!"
meta_description: "This time the last one is the real last one!"
meta_image: "smokingkills.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards

